//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiftChoice.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class BannerTbl
    {
        public HttpPostedFileBase Image { get; set; }
        public long BannerId { get; set; }
        public Nullable<long> MainCateId { get; set; }
        public string BUrl { get; set; }
        public string BannerImage { get; set; }
        public Nullable<long> Priority { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> Create_at { get; set; }
        public Nullable<System.DateTime> Update_at { get; set; }
    }
}
