//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiftChoice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSubTitleDetailTbl
    {
        public int BSubDId { get; set; }
        public Nullable<int> MainCateId { get; set; }
        public Nullable<int> QueryId { get; set; }
        public Nullable<int> BSubId { get; set; }
        public string kSubTitle { get; set; }
    }
}
