//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiftChoice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCKeywordTbl
    {
        public long MCkeywordId { get; set; }
        public Nullable<long> MainCateId { get; set; }
        public Nullable<long> KeywordId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Menu { get; set; }
        public Nullable<bool> Fliter { get; set; }
        public Nullable<bool> MenuFilter { get; set; }
    
        public virtual KeywordTbl KeywordTbl { get; set; }
        public virtual MainCateTbl MainCateTbl { get; set; }
    }
}
