
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GiftChoice.Models
{

using System;
    using System.Collections.Generic;
    
public partial class OrderMainTbl
{

    public long MorderId { get; set; }

    public Nullable<long> RUserId { get; set; }

    public Nullable<bool> Delivery { get; set; }

    public Nullable<bool> Dispatch { get; set; }

    public Nullable<bool> Active { get; set; }

    public Nullable<bool> Cancel { get; set; }

    public Nullable<System.DateTime> Create_at { get; set; }

    public Nullable<double> TotalAmount { get; set; }

}

}
