
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GiftChoice.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ProductDetailTbl
{

    public long PdId { get; set; }

    public Nullable<long> ProductId { get; set; }

    public string ProductType { get; set; }

    public string Price { get; set; }

    public Nullable<int> SizeId { get; set; }

    public string SizeName { get; set; }

    public Nullable<long> Priority { get; set; }

    public Nullable<bool> Active { get; set; }

}

}
