
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GiftChoice.Models
{

using System;
    using System.Collections.Generic;
    
public partial class UserRegister
{

    public long RUserId { get; set; }

    public string UName { get; set; }

    public string MobileNo { get; set; }

    public string UEmail { get; set; }

    public string UAddress { get; set; }

    public string City { get; set; }

    public string UState { get; set; }

    public string Pincode { get; set; }

    public Nullable<bool> Active { get; set; }

    public Nullable<System.DateTime> Create_at { get; set; }

}

}
