//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiftChoice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VProduct
    {
        public long ProductId { get; set; }
        public Nullable<long> MainCateId { get; set; }
        public string ProductTitle { get; set; }
        public Nullable<double> Price { get; set; }
        public string PUrl { get; set; }
        public string PLabel { get; set; }
        public string PDesc { get; set; }
        public Nullable<long> Priority { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> Create_at { get; set; }
        public Nullable<System.DateTime> Update_at { get; set; }
        public Nullable<long> UserID { get; set; }
        public long PKeywordId { get; set; }
        public Nullable<long> Expr1 { get; set; }
        public Nullable<long> KeywordId { get; set; }
        public Nullable<bool> Expr2 { get; set; }
        public long Expr3 { get; set; }
        public string Keyword { get; set; }
        public string KUrl { get; set; }
        public Nullable<System.DateTime> Expr4 { get; set; }
        public Nullable<System.DateTime> Expr5 { get; set; }
        public Nullable<bool> Expr6 { get; set; }
        public Nullable<long> Expr7 { get; set; }
        public Nullable<long> Expr8 { get; set; }
        public long Expr9 { get; set; }
        public string MTitle { get; set; }
        public string MUrl { get; set; }
        public Nullable<bool> Expr10 { get; set; }
        public Nullable<long> Expr11 { get; set; }
        public string MImage { get; set; }
        public Nullable<long> Expr13 { get; set; }
        public Nullable<System.DateTime> Expr12 { get; set; }
        public Nullable<System.DateTime> Expr14 { get; set; }
    }
}
